# Generated by Django 5.0.1 on 2025-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id_caixa', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'db_table': 'caixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nif_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('pnome_cliente', models.CharField(max_length=10)),
                ('unome_cliente', models.CharField(max_length=10)),
                ('contacto_tel', models.CharField(max_length=20)),
                ('morada', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('password_client', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('pnome_funcionario', models.CharField(max_length=10)),
                ('unome_funcionario', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=25)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
    ]
